#! /bin/sh

sxhkd &

### General ###

bspc monitor -d HOM WEB DEV TRM R\&R RND
# bspc monitor -d 

bspc config border_width        10
bspc config window_gap          20

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

### Mouse ###

bspc config focus_follows_pointer true

bspc rule -a Firefox desktop='^2'

bspc config super mod4
feh --bg-fill ~/Pictures/wallpaper.jpg
compton --config ~/.config/compton.conf -b
polybar top -r &

### COLORS ###

bspc config normal_border_color \#282828
# bspc config active_border_color \#C0C5CE
bspc config focused_border_color \#C0C5CE
bspc config urgent_border_color \#EC5F67
