#! /bin/sh

sxhkd &

### General ###

# bspc monitor -d HOM WEB DEV TRM R\&R RND
bspc monitor -d      

bspc config border_width        3
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

### Mouse ###

bspc config focus_follows_pointer true

bspc rule -a Firefox desktop='^2'
bspc rule -a Steam desktop='^5'
# bspc rule -a virtualbox desktop='^6'

bspc config super mod4
polybar top -r &
feh --bg-fill ~/Pictures/Wallpapers/wallpaper.jpg
# feh --bg-fill ~/Pictures/Wallpapers/wallpaper.png
compton # --config ~/.config/compton.conf -b

### COLORS ###

bspc config normal_border_color \#1b2b34
# bspc config active_border_color \#C0C5CE
bspc config focused_border_color \#c0c5ce
bspc config urgent_border_color \#ec5f67
