#!/bin/bash

export SHELL="/bin/zsh"
export BROWSER="firefox"
export acmeshall=$SHELL
export tabstop=4

if [ -z $ACME_FONT ]; then
	export ACME_FONT="/mnt/font/Menlo-Regular/14a/font"
fi

if [ "$(pgrep plumber)" ]; then
	echo "plumber is running"
else
	echo "starting plumber..."
	plumber
fi

acme -a -f $ACME_FONT $1 &
