# emacs makefile for exwm

XSESSIONS_DIR ?= /usr/share/xsessions

setup-exwm:
	cp ./exwm/emacs.desktop $XSESSIONS_DIR
	chmod +x ./exwm/exwm.sh
	cp config.org config.org.bu
	cp config.exwm.org config.org

